...

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -2,7 +2,7 @@
 
 # author:       Li Junhao           l@x-cmd.com    edwinjhlee.github.io
 
-# Section: work
+# Section: main
 
 xrc param/v0
 
@@ -69,100 +69,53 @@ ___tldr_update()(
     fi
 
     if cd "$_______X_CMD_TLDR_ROOT/$version/pages" && tar xvf pages.tgz 2>/dev/null; then
-        printf "Already upload version to %s.\n" "$version"
+        printf "Already upload version to %s.\n" "$version" >&2
     fi
 
 )
+
+___tldr_current_or_update(){
+    local version
+    if ! version="$(___tldr_current)"; then
+        if ! ___tldr_update; then
+            return 1
+        fi
+        ___tldr_cureent
+        return
+    else
+        printf "%s" "$version"
+    fi
+}
 
 ___tldr_use(){
     :
 }
 
-___tldr_ls(){
-    :
-}
+___tldr_ls()(
+    local version
+    version="$(___tldr_current_or_update)" || return
+
+    cd "$_______X_CMD_TLDR_ROOT/$version/pages/"
+    local cmd="${1}"
+    case "$cmd" in
+        "")     ls */* ;;
+        */*)    ls */* | grep "$cmd.md" ;;
+        *)      ls */* | grep "\/$cmd.md" ;;
+    esac
+)
 
 ___tldr_look(){
-    :
-}
+    cand="$( ___tldr_ls "$@" )"
+    local num
+    num="$(printf "%s" "$cand" | awk 'END{ print NR; }')"
 
-# EndSection
-
-
-# Section: man
-
-___advise_man_exists(){
-    [ -d "$___X_CMD_ROOT/.tmp/advise/src" ]
-}
-
-___advise_man_update(){
-    local ___X_CMD_CURL_UPDATE="${___X_CMD_CURL_UPDATE}"
-
-    local CACHE="$___X_CMD_ROOT/.tmp/tldr/all.tar.gz"
-    local srcfolder="$___X_CMD_ROOT/.tmp/tldr/src"
-
-    local url="https://gitee.com/x-cmd/advise/raw/main/dist/all.tgz"
-    if [ "$___X_CMD_IN_CHINA_NET" != 1 ]; then
-        url="https://raw.githubusercontent.com/x-cmd/theme/advise/dist/all.tgz"
-    fi
-
-    if ___x_cmd_curl "$url"; then
-        [ -d "$srcfolder" ] && rm -rf "$srcfolder"
-        mkdir -p "$srcfolder"
-        tar -C "$srcfolder" xvf "$CACHE"
-    fi
-}
-
-___advise_man_ls(){
-    if ___advise_man_exists || ___advise_man_update; then
-        ls "$___X_CMD_ROOT/.tmp/advise/src"
-    fi
-}
-
-___advise_man_which(){
-    local name="${1:?Provide name}"
-    if ___advise_man_exists || ___advise_man_update; then
-        local p="$___X_CMD_ROOT/.tmp/advise/src/$name/advise.json"
-        [ -f "$p" ] && printf "%s" "$p"
-    fi
-
-    return 1
-}
-
-# ___advise_man_load(){
-#     local cmd="${1:?Provide cmd}"
-#     local p="$(___advise_man_which "$cmd")"
-#     if [ ! -f "$p" ]; then
-#         printf "%s\n" "$cmd.json Not found. You could try 'advise man update' for updates." >&2
-#         return 1
-#     fi
-#     compgen "___advise_man_completer" "$cmd"
-# }
-
-___advise_man_load(){
-    local i
-    for i in $(___advise_man_ls); do
-        if s=$(complete -p "$i" 1>/dev/null 2>&1); then
-            [[ "$s" == *___advise_completer* ]] && continue
-        fi
-        compgen "___advise_man_completer" "$i"
-    done
-}
-
-___advise_man_completer() {
-    # Interesting ... Passing
-    ___ADVISE_RUN_CMD_FOLDER="$___X_CMD_ROOT/.tmp/advise/src/" ___advise_run ""
-}
-
-___advise_man(){
-    local op="${1:?Provide subcommand}"; shift
-    case "$op" in
-        ls)         ___advise_man_ls ;;
-        update)     ___advise_man_update ;;
-        which)      ___advise_man_which "$@" ;;
-        load)       ___advise_man_load "$@" ;;
-        *)          ___advise_man_load "$op" "$@" ;;
+    case $num in
+        0)  printf "Not found.\n" >&2; return 1 ;;
+        1)  cat "$_______X_CMD_TLDR_ROOT/$(___tldr_current)/pages/$cand" ;;
+        *)  printf "Found %s:\n %s\n" "$num" "$cand"; >&2 return 1 ;;
     esac
 }
 
 # EndSection
+
+
